### ISSUE TITLE
Mount a local directory and login as the user

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/footloose#11]
A very frequent test case is to be able to mount a local directory (say a git checkout, or `$HOME`) to expose parts of the host fs inside the machine.

There's one detail though, we are likely to want that, when writing files to that mount, we want to write them with the `id`, `gid` of the user of the host machine.

**Comment by dlespiau** [comment]
#43 has one idea for what the configuration for this feature could look like (`mirrorUser`):

```
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 3
  spec:
    image: quay.io/footloose/centos7
    name: node%d
    portMappings:
    - containerPort: 22
    mirrorUser: true
```
