### ISSUE TITLE
Expose user creation in footloose.yaml

### ISSUE THREAD

**Issue by dlespiau** [dlespiau/footloose#43]
It'd be nice to be able to provision non-root users when creating container machines so we can login as non-root. Maybe something like:

```
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 3
  spec:
    image: quay.io/footloose/centos7
    name: node%d
    portMappings:
    - containerPort: 22
    groups:
    - name: damien
      id: 1001
    users:
    - name: damien 
      id: 1001
      groups:
      - damien     
```

This has some overlap with #11. I'm not sure how useful it is to create a user with a fixed `(id,gid)` compared to a dynamic user that mirrrors the current user inside the container.

Maybe we want both and they should different features. The issue with with implementing #11 with the idea above is that the configuration file would change depending on which machine/user is using the configuration.

This could mean #11 may be implemented in a different way:
```
cluster:
  name: cluster
  privateKey: cluster-key
machines:
- count: 3
  spec:
    image: quay.io/footloose/centos7
    name: node%d
    portMappings:
    - containerPort: 22
    mirrorUser: true
```

`mirrorUser` (or any better name!) would instruct footloose to mirror the user running footloose inside the CM.
